name: merge to downstream branches

on:
  push:
    branches:
      - 'master'
      - 'release/*'
      - 'develop'

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    # checks out out repo to $GITHUB_WORKSPACE
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: ./merge-downstream
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}