name: merge to downstream branches

on: [push]

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    # checks out out repo to $GITHUB_WORKSPACE
    - uses: actions/checkout@v1
    - uses: ./merge-downstream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}